language: R
cache: packages
sudo: required
warnings_are_errors: true

r_packages:
  - covr
  - devtools

os:
  - linux

r:
 - release
 - devel

##grep data from testthat
after_success:
- Rscript -e 'covr::codecov()'

##create notification
notifications:
  email:
    recipients:
      - johannes.friedrich@posteo.de
    on_success: change
    on_failure: change
